-- SP para procesar el dia de ahorro de las CO

USE Proyecto
GO

CREATE PROCEDURE dbo.AhorroCO
				@InIdCO INT
				--,@InFechaActual DATE
AS 
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		DECLARE @MontoAhorro MONEY
				,@IdCA INT
				,
		SET TRANSACTION ISOLATION LEVEL READ COMMITTED
		BEGIN TRANSACTION T1;

		COMMIT TRANSACTION T1;
	END TRY

	BEGIN CATCH
		IF @@tRANCOUNT>0
			ROLLBACK TRAN T1;
	END CATCH
	SET NOCOUNT OFF
END