USE Proyecto
GO

CREATE PROCEDURE EditParentezco
	@inNuevoParentezco VARCHAR(40)
	, @inIdBen INT
	, @outCodeResult INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRANSACTION T1
			UPDATE Beneficiario 
			SET ParentezcoId=(SELECT Id FROM Parentezco WHERE Nombre=@inNuevoParentezco) 
			WHERE Id=@inIdBen
		COMMIT TRANSACTION t1
	END TRY
	BEGIN CATCH
		IF @@tRANCOUNT>0
			ROLLBACK TRAN T1;
		--INSERT EN TABLA DE ERRORES;
		SET @outCodeResult=50005;
	END CATCH
	SET NOCOUNT OFF
END