USE Proyecto
GO

CREATE PROCEDURE EditNombre
	@inNuevoNombre VARCHAR(40)
	, @inIdBen INT
	, @outCodeResult INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRANSACTION T1
			UPDATE Persona SET Nombre=@inNuevoNombre 
			WHERE Id=(SELECT IdPersona FROM Beneficiario WHERE Id=@inIdBen)
		COMMIT TRANSACTION t1
	END TRY
	BEGIN CATCH
		IF @@tRANCOUNT>0
			ROLLBACK TRAN T1;
		--INSERT EN TABLA DE ERRORES;
		SET @outCodeResult=50005;
	END CATCH
	SET NOCOUNT OFF
END