CREATE PROCEDURE EditFecha1CO
	@inNuevaFechaI VARCHAR(40)
	, @inIdCO INT
	, @outCodeResult INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRANSACTION T1
			UPDATE CuentaObjetivo SET FechaInicio=@inNuevaFechaI 
			WHERE Id=@inIdCO;
		COMMIT TRANSACTION t1
	END TRY
	BEGIN CATCH
		IF @@tRANCOUNT>0
			ROLLBACK TRAN T1;
		--INSERT EN TABLA DE ERRORES;
		SET @outCodeResult=50005;
	END CATCH
	SET NOCOUNT OFF
END