USE Proyecto
GO

CREATE PROCEDURE EliminarBeneficiario
	@inIdBen INT
	, @outCodeResult INT OUTPUT
AS
BEGIN
	SET NOCOUNT ON
	BEGIN TRY
		BEGIN TRANSACTION T1
			UPDATE dbo.Beneficiario 
			SET Activo=0 
			WHERE Id=@inIdBen
			UPDATE dbo.Beneficiario 
			SET FechaDesactivacion=GETDATE() 
			WHERE Id=@inIdBen
		COMMIT TRANSACTION t1
	END TRY
	BEGIN CATCH
		IF @@tRANCOUNT>0
			ROLLBACK TRAN T1;
		--INSERT EN TABLA DE ERRORES;
		SET @outCodeResult=50005;
	END CATCH
	SET NOCOUNT OFF
END